### ISSUE TITLE
<Append>/</Append> doesn't work

### ISSUE THREAD

**Issue by plojewski** [nawork/nawork-uri#10]
Hi again :)
When I click a link on site, for example About company it works ok, it opens:

http://example.com/about-company/

but when I change URL to http://example.com/about-company (remove /) and tap Enter it doesn't redirect to http://example.com/about-company/ again.

And the second problem. I've got in configuration:

    <General>
        <Append>/</Append>
        <RedirectStatus>301</RedirectStatus>
    </General>

    <castTypeToInt>1</castTypeToInt>
    <castLToInt>1</castLToInt>
    <redirectOnParameterDiff>1</redirectOnParameterDiff>

    <PageNotFound>
        <Status>HTTP/1.0 404 Not Found</Status>
		<Behavior>Redirect</Behavior>
		<Value>/404/</Value>
	</PageNotFound>

but when server uses fastcgi it doesn't redirect to /404/, but I've got 500 error and message in error log:

**aborted: error parsing headers: malformed header '301'**

Could you please help me?

**Comment by thommyhh** [comment]
The behaviour of treating urls with or without "/" at the end the same was introduced due to some browser not sending the last "/" to the server. I've plans to change/improve this in the 3.x version. If you like redirect those urls in your case, you've to add a redirect rule in the web servers configuration using a regular expression.

At the bug with the corrupt header I will take a look. This should of course not happen.

Btw, a redirect isn't the best option for a 404, because it is not a 404 for search engines. ;-)

**Comment by plojewski** [comment]
> Btw, a redirect isn't the best option for a 404, because it is not a 404 for search engines. ;-)
I know, that's why I'm waiting for nawork-uri better 404 support :)

I've got site with many trees and domains, and many languages per domain and need 404 per domain + per language. So for now redirect is the only possibility (can't be only message).

For 404 pages it could be set config.additionalHeaders = HTTP/1.0 404 Not Found in typoscript so Google see it as 404 :)

**Comment by thommyhh** [comment]
Ok, I will improve the possibilities with the 404 handling, but it is only planned for the 3.x branch. The 2.x will only get bug and security fixes.

Btw: The corrupt/malformed redirect header for the 404 handling should be fixed now. Please try the current nawork_uri_2.7 branch and tell me if this solves your problem with the fastcgi server.

**Comment by plojewski** [comment]
I'm trying to check this, but I can't install ext by Upload in my case. Could you please publish this version in ter?

**Comment by thommyhh** [comment]
Couldn't you use the git checkout? I was trying to avoid publishing an untested change. What setup are you using?

**Comment by plojewski** [comment]
No, I have to install this ext from ter. It results from the specific project. I changed line:

\Nawork\NaworkUri\Utility\GeneralUtility::sendRedirect($path, 301); // send headers and exits

to:

\Nawork\NaworkUri\Utility\GeneralUtility::sendRedirect($path, HttpUtility::HTTP_STATUS_301); // send headers and exit

in file. Is it the only one change?

**Comment by thommyhh** [comment]
Yes, this is the only change. It is changed in two places, the 404 and 403 handling, but you will though only need the change in line 412.

Does it work then?

**Comment by thommyhh** [comment]
I just releases 2.7.6 containing the bugfix for the redirect header. Does this solve your problem?

Furthermore is there now a solution for the translated 404 pages: https://github.com/nawork/nawork-uri/wiki/Page-not-found-handling#advanced-page-not-found-handling-since-version-310.

**Comment by plojewski** [comment]
I'll verify it and let you know

**Comment by thommyhh** [comment]
Any news on this?

**Comment by thommyhh** [comment]
The <Append> behaviour is changed as bugfix in nawork_uri_3.0, nawork_uri_3.1 and master branches. The url is not treated as normal anymore, but is redirect to the correct url with <Append> value. This happens only, if the url with <Append> is found in the database.
