### ISSUE TITLE
Issues with typoscript_rendering extension from Helmut Hummel

### ISSUE THREAD

**Issue by sascha-schieferdecker** [nawork/nawork-uri#13]
When using the typoscript_rendering extension to generate AJAX links, nawork_uri generates an infinite redirect loop with the TYPO3 default .htaccess:

http://xxx.xxx.de/?tx_typoscriptrendering[context]={%22record%22:%22tt_content_17501%22,%22path%22:%22tt_content.list.20.citkobookmarks_output%22}&tx_citkobookmarks_output[controller]=Bookmarks&tx_citkobookmarks_output[bookmark]=2&tx_citkobookmarks_output[action]=delete&cHash=a0b06b5c823e07be1c8c87df92ce7ac5

Is there any way to stop nawork_uri from rewriting urls if there is a certain argument in the URL? 

The URL works with deinstalled nawork-uri and with realurl. But I'd rather use nawork_uri, as it looks very promising :)

**Comment by thommyhh** [comment]
No, they there is no way stopping processing. I think it does not make sense.

But I think, I have fixed the issue with Versions 2.7.9, 3.0.7 and 3.1.6. Please try the correspondig version.

**Comment by sascha-schieferdecker** [comment]
I can confirm 3.1.6 fixes the issue, thanks a lot and thanks for providing an alternative to realurl.
