### ISSUE TITLE
Error when no domain record found

### ISSUE THREAD

**Issue by tmotyl** [nawork/nawork-uri#14]
when there is no domain record, an error is thrown when accessing backend modules (URl management or Redirect Management)

```
Uncaught TYPO3 Exception
Call to a member function getUid() on null 

Error thrown in file
typo3conf/ext/nawork_uri/Classes/Domain/Model/Filter.php in line 171.

18 Nawork\NaworkUri\Domain\Model\Filter::jsonSerialize()
17 json_encode(Nawork\NaworkUri\Domain\Model\Filter)

typo3conf/ext/nawork_uri/Classes/Controller/UrlController.php:
00191:   $this->view->assignMultiple(
00192:             [
00193:                 'filter' => json_encode($filter),
00194:                 'userSettings' => json_encode($this->userSettings),
00195:                 'labels' => $this->buildLabelsObject()

```

**Comment by thommyhh** [comment]
As a domain record is required for the frontend to work, I'd suggest to show a an error message, when there is no domain record set, like the one for "Please select a page".

What do you think?

**Comment by tmotyl** [comment]
sounds good :)

**Comment by thommyhh** [comment]
I fixed this on the branches nawork_uri_3.0, nawork_uri_3.1 and master. The modules shown flash messages now to indicate the mistake or error.
