### ISSUE TITLE
Non-Admins are not able to use the redirect module

### ISSUE THREAD

**Issue by SicorDev** [nawork/nawork-uri#21]
Non-Admin users are only able to create redirects using the redirection module. There is no possibility to edit or delete the records. (The contextmenu is empty/doesn't work)

Admin users however can edit the redirects, but its not possible to delete a record using the contextmenu. (The only way to delete a record is to edit it and then use the bin button)

**Comment by thommyhh** [comment]
@SicorDev I kind of refactored the context menu generation to check the necessary permissions for editing the url table and the necessary options. As far as I have tested, this makes both modules work for editors and admins.

Can you please try the current master/3.1.x/3.0.x branch, if it work for you now?

**Comment by SicorDev** [comment]
@thommyhh 
I've tested the 3.1.x branch and it seemed to work pretty well.

**Comment by thommyhh** [comment]
I released 3.0.9 and 3.1.8, so closing this.
