### ISSUE TITLE
404 pages for sites with sublanguages

### ISSUE THREAD

**Issue by chimpanze** [nawork/nawork-uri#3]
Hi!

Currently nawork_uri handles the 404 pages per domain. So if you have www.test.de and www.test.com it would display the correct 404 pages. But if you have more than one language for www.test.com there is no possibility to display the correct 404 page for that language.

www.test.com => www.test.com/404
www.test.com/it => www.test.com/it/404
www.test.com/fr => www.test.com/fr/404

I think the best option would be, that the 404 pages can be defined via the configuration per language and domain.

**Comment by plojewski** [comment]
Could we expect that missing functionality please?

**Comment by thommyhh** [comment]
I have some idea how to accomplish this, but I need to think about it some more.

**Comment by plojewski** [comment]
OK, nice to hear. The ext is great BTW :)

**Comment by thommyhh** [comment]
There is now a solution to this use case. It is called "advanced page not found handling" (https://github.com/nawork/nawork-uri/wiki/Page-not-found-handling#advanced-page-not-found-handling-since-version-310).

Please take a look, if the basic implementation fits your needs.
