### ISSUE TITLE
Clearing cache error

### ISSUE THREAD

**Issue by plojewski** [nawork/nawork-uri#6]
Hello,
I use Typo3 6.2.27 and nawork_uri 2.7.4. When I click "Clear URL configuration cache" an error accurred:

No backend function registered for ajaxID "ajaxID=tx_naworkuri::clearUrlConfigurationCache".

![zrzut ekranu 2016-12-15 o 15 33 08](https://cloud.githubusercontent.com/assets/7590893/21227851/da2ac4d2-c2db-11e6-9a26-b5da7be61621.png)

Could you please help me?

**Comment by thommyhh** [comment]
Hi Piotr,

I just fixed it and published version 2.7.5. It is already available via composer/Packagist and should soon be available in the TER.

Best regards
Thorben

**Comment by plojewski** [comment]
Thank you! It works now.
